server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # Application Angular (SPA) : on renvoie toujours index.html pour que le
    # routeur côté client prenne en charge les URL (/login, /books, /users, ...).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
